### ISSUE TITLE
Got error when I try to set log-rotate-age

### ISSUE THREAD

**Issue by zackliu** [Azure/fluentd-plugin-mdsd#59]
If I start fluentd with `/opt/td-agent/embedded/bin/fluentd --log /var/log/td-agent/td-agent.log --log-rotate-age daily` then I will get an error:

> /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mdsd-0.1.8.pre.build.master.69/lib/fluent/plugin/out_mdsd.rb:46:in `configure': undefined method `path' for #<Fluent::LogDeviceIO:0x00007f7461b6c358> (NoMethodError)
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin.rb:164:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:130:in `add_match'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:72:in `block in configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `each'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/agent.rb:64:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/root_agent.rb:112:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:131:in `configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/engine.rb:96:in `run_configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:795:in `run_configure'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:579:in `dry_run'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:597:in `supervise'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/supervisor.rb:502:in `run_supervisor'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/bin/fluentd:8:in `<top (required)>'
        from ./fluentd:23:in `load'
        from ./fluentd:23:in `<main>'

But if I remove the `--log-rotate-age` option, it works well. Could you help me to resolve the problem?

**Comment by zackliu** [comment]
One new discovery. If I try to output to stdout, I can also get the error `/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-mdsd-0.1.8.pre.build.master.69/lib/fluent/plugin/out_mdsd.rb:46:in `configure': undefined method `path' for #<IO:<STDOUT>> (NoMethodError)`
