### ISSUE TITLE
td-agent failed to start with the plugin when changing td-agent.conf

### ISSUE THREAD

**Issue by sharadkejriwal** [Azure/fluentd-plugin-mdsd#64]
After changin td-agent.conf as described at https://genevamondocs.azurewebsites.net/collect/instrument/linux/fluentd.html
, on starting td-agent getting the below error:

-- Unit td-agent.service has begun starting up.
Starting td-agent: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-mdsd-0.1.9.pre.build.master.71/lib/fluent/plugin/out_mdsd.rb:16:in `require_relative': /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-mdsd-0.1.9.pre.build.master.71/lib/fluent/plugin/Liboutmdsdrb.so: undefined symbol: rb_str_new_static - /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-mdsd-0.1.9.pre.build.master.71/lib/fluent/plugin/Liboutmdsdrb.so (LoadError)
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-mdsd-0.1.9.pre.build.master.71/lib/fluent/plugin/out_mdsd.rb:16:in `initialize'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:132:in `new'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:132:in `new_impl'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin.rb:59:in `new_output'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:131:in `add_match'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:64:in `block in configure'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:57:in `each'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/agent.rb:57:in `configure'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/root_agent.rb:86:in `configure'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/engine.rb:129:in `configure'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/engine.rb:103:in `run_configure'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:489:in `run_configure'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:160:in `block in start'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:366:in `call'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:366:in `main_process'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:339:in `block in supervise'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:338:in `fork'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:338:in `supervise'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/supervisor.rb:156:in `start'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/bin/fluentd:5:in `<top (required)>'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/bin/fluentd:23:in `load'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /usr/sbin/td-agent:7:in `load'
Apr 04 17:03:34 TestVM3 td-agent[9948]:         from /usr/sbin/td-agent:7:in `<main>'
Apr 04 17:03:34 TestVM3 td-agent[9948]:  * td-agent
Apr 04 17:03:34 TestVM3 systemd[1]: td-agent.service: Control process exited, code=exited status=1
Apr 04 17:03:34 TestVM3 systemd[1]: Failed to start LSB: data collector for Treasure Data.
-- Subject: Unit td-agent.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit td-agent.service has failed.
--
-- The result is failed.
Apr 04 17:03:34 TestVM3 systemd[1]: td-agent.service: Unit entered failed state.
Apr 04 17:03:34 TestVM3 systemd[1]: td-agent.service: Failed with result 'exit-code'.

**Comment by sharadkejriwal** [comment]
I am using td-agent version 2.3.6

**Comment by sharadkejriwal** [comment]
This worked with plugin version 0.1.6(https://github.com/Azure/fluentd-plugin-mdsd/releases/download/0.1.6/fluent-plugin-mdsd-0.1.6.master.54-td.amd64.gem)
and not 0.1.9. But, plugin compatability with td-agent version whould be mentioned somewhere.
